apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-chart.fullname" . }}
data:
  {{- toYaml .Values.configmap.data | nindent 2 }}
  URI_GATEWAY: http://{{ include "user-chart.fullname" . }}-gateway
  URI_ISSUER: http://{{ include "user-chart.fullname" . }}-auth/auth
  URI_USER-APP: http://{{ include "user-chart.fullname" . }}-user