apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-chart.fullname" . }}
data:
  URI_USER-APP: http://{{ include "user-chart.fullname" . }}-user
  {{- toYaml .Values.configmap.data | nindent 2 }}
