{{- if .Values.ingress.enabled -}}
{{- $fullName := include "user-chart.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "user-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-gateway
                port:
                  number: {{$svcPort}}
          - path: /auth
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $fullName }}-auth
                port:
                  number: {{$svcPort}}
    {{- end }}
{{- end }}
