server:
  port: 8090

uri:
  issuer: http://localhost:9000
  user-app: http://localhost:8080
  host: localhost

spring:
  application:
    name: gateway
  security:
      oauth2:
        client:
          registration:
            gateway:
              provider: my-oidc-provider
              client-id: gateway
              client-secret: gateway-secret
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
              scope: openid
          provider:
            my-oidc-provider:
              issuer-uri: ${uri.issuer}

  cloud:
     gateway:
       routes:
          - id: otus-user-app-registration
            uri: ${uri.user-app}
            order: 1
            predicates:
              - Host=${uri.host}
              - Path=/api/registration
          - id: otus-user-app-api
            uri: ${uri.user-app}
            order: 2
            predicates:
              - Host=${uri.host}
              - Path=/api/user/**
            filters:
              - TokenRelay=
              - RemoveRequestHeader=Cookie